id: P6A46631A
initial_creation_type: ocr
source_metadata:
  volumes:
    942ef01e6ee3498d99a8bab85efb8487:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: ཚུལ་ཁྲིམས་ཀྱི་གཏམ།
      total_pages: 1144
      volume_number: 96
